CareersListing/Models/Company.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CareersListing.Models
{
    public class Company
    {
        public int Id { get; set; }
        public ApplicationUser Employer { get; set; }
        public string EmployerId { get; set; }

        [Required]
        [MaxLength(100, ErrorMessage = "Company name must not be more than 100 characters")]
        public string Name { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Url]
        public string Website { get; set; }

        public string Street { get; set; }

        [Required]
        [MaxLength(100, ErrorMessage = "City must not be more than 100 characters")]
        public string City { get; set; }

        [Required]
        public string Country { get; set; }
        public string CompanyCertificate { get; set; }
        public string Logo { get; set; }

        [Required]
        public DateTime DateRegistered { get; set; }

        public Vacancy Vacancies { get; set; }

    }
}

CareersListing/ViewModels/CompanyViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CareersListing.ViewModels
{
    public class CompanyViewModel
    {

        public int Id { get; set; }

        [Required]
        [MaxLength(100, ErrorMessage = "Company name must not be more than 100 characters")]
        public string Name { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Url]
        public string Website { get; set; }

        public string Street { get; set; }

        [Required]
        [MaxLength(100, ErrorMessage = "City must not be more than 100 characters")]
        public string City { get; set; }

        [Required]
        public string Country { get; set; }

        [Display(Name = "Certificate PDF")]
        public IFormFile CompanyCertificate { get; set; }
        public string ExistingCertificate { get; set; }

        [Display(Name = "Logo")]
        public IFormFile Logo { get; set; }
        public string ExistingLogo { get; set; }

        public DateTime DateRegistered { get; set; }

        public List<ListCompaniesViewModel> ListOfCompanies { get; set; }

        public CompanyViewModel()
        {
            DateRegistered = DateTime.Now;
            ListOfCompanies = new List<ListCompaniesViewModel>();
        }

    }
}

CareersListing/ViewModels/Employer.cs
namespace CareersListing.ViewModels
{
    public class Employer
    {
    }
}

CareersListing/Controllers/EmployerController.cs
using CareersListing.Models;
using CareersListing.Utilities;
using CareersListing.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CareersListing.Controllers
{
    [Authorize(Roles = "Employer, Super Admin, Admin")]
    public class EmployerController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly ICompanyRepo _companyRepo;
        private readonly ILogger<EmployerController> _logger;
        private readonly IVacancyRepo _vacancyRepo;

        public EmployerController(RoleManager<IdentityRole> roleManager,
                                        UserManager<ApplicationUser> userManager,
                                        IHostingEnvironment hostingEnvironment,
                                        ICompanyRepo companyRepo, ILogger<EmployerController> logger,
                                        IVacancyRepo vacancyRepo)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _hostingEnvironment = hostingEnvironment;
            _companyRepo = companyRepo;
            _logger = logger;
            _vacancyRepo = vacancyRepo;
        }
        // ----------------------------------------------------------------------------------------

        // Vacancies (GET)
        [HttpGet]
        public async Task<IActionResult> Vacancies()
        {
            JobVacancyViewModel model = new JobVacancyViewModel();
            List<ListCompaniesViewModel> listOfCompanies = new List<ListCompaniesViewModel>();
            List<ListOfJobVacancies> listOfVacancies = new List<ListOfJobVacancies>();
            
            var user = await _userManager.GetUserAsync(User);
            ICollection<Company> companies = null;
            ICollection<Vacancy> vacancies = null;
            if (await _userManager.IsInRoleAsync(user, "Super Admin") || await _userManager.IsInRoleAsync(user, "Admin"))
            {
                companies = await _companyRepo.GetAllCompanies();
                vacancies = await _vacancyRepo.GetAllVacancies();
            }
            else 
            { 
                companies = await _companyRepo.GetAllCompaniesByEmployer(_userManager.GetUserId(User));
                vacancies = await _vacancyRepo.GetAllVacanciesByEmployer(_userManager.GetUserId(User));
            }
            

            // add the list of companies to ViewBag.CompanyList
            foreach (var company in companies)
            {
                var row = new ListCompaniesViewModel
                {
                    Id = company.Id,
                    Name = company.Name,
                };

                listOfCompanies.Add(row);
            }

            // add list of job vacancies to model
            foreach(var vacancy in vacancies)
            {
                var row = new ListOfJobVacancies
                {
                    Id = vacancy.Id,
                    JobTitle = vacancy.JobTitle,
                    Company = vacancy.Company,
                    Location = vacancy.Location,
                    Salaries = vacancy.SalaryScale,
                    Duration = vacancy.JobDuration,
                    DateExpired = vacancy.DateExpired
                };
                model.Vacancies.Add(row);
            }

            ViewBag.CompanyList = listOfCompanies;
            return View(model);
        }
        // Company (POST) ---------------------------------------------------------------------
        [HttpPost]
        public async Task<IActionResult> Vacancies(JobVacancyViewModel model, int? id)
        {
            if (ModelState.IsValid)
            {
                var vacancy = new Vacancy
                {
                   CompanyId = model.CompanyId,
                   EmployerId = _userManager.GetUserId(User),
                   JobTitle = model.JobTitle,
                   JobDuration = model.JobDuration,
                   JobFunction = model.JobFunction,
                   Industry = model.Industry,
                   Location = model.Location,
                   SalaryScale = model.SalaryScale,
                   DateExpired = model.DateExpired,
                   DatePosted = model.DatePosted,
                   Description = model.Description
                };

                // id value is binding from the edit view 
                bool result;
                if (id.HasValue)
                {
                    vacancy.Id = (int)id;
                    result = await _vacancyRepo.UpdateVacancy(vacancy);
                }
                else
                {
                    result = await _vacancyRepo.AddVacancy(vacancy);
                }

                if (!result)
                {
                    _logger.LogError($"Error saving vacancy to database!");
                    ViewBag.ErrorMessage = "Failed to save vacancy to database!";
                }
                return RedirectToAction("Vacancies");
            };
            return View(model);
        }
        //--------------------------------------------------------------------------------------------------------

        // Delete company (POST)
        [HttpPost]
        public async Task<IActionResult> DeleteVacancy(int id)
        {
            var vacancy = await _vacancyRepo.GetVacancy(id);
            if (vacancy != null)
            {
                var result = await _vacancyRepo.DeleteVacancy(vacancy);
                if (result)
                {
                    return RedirectToAction("Vacancy");
                }
                _logger.LogError($"Error deleting vacancy!");
                ViewBag.ErrorMessage = "Failed to delete vacancy!";
            }
            return View();
        }
        //--------------------------------------------------------------------------------------------------------

        // Company (GET)
        [HttpGet]
        public async Task<IActionResult> Company(int? id)
        {
            CompanyViewModel model = new CompanyViewModel();
            if (id.HasValue)
            {
                var companyToEdit = await _companyRepo.GetCompany(id);
                if (companyToEdit == null)
                {
                    ViewBag.ErrorMessage = $"Company with id : {id} was not found!";
                    return RedirectToAction("NotFound");
                }
                    // add the details of company to edit to model
                    model.Id = companyToEdit.Id;
                    model.Name = companyToEdit.Name;
                    model.Email = companyToEdit.Email;
                    model.Website = companyToEdit.Website;
                    model.Street = companyToEdit.Street;
                    model.City = companyToEdit.Website;
                    model.Country = companyToEdit.Country;
                    model.ExistingLogo = companyToEdit.Logo;
                    model.ExistingCertificate = companyToEdit.CompanyCertificate;
            }

            // add the list of companies to model
            var user = await _userManager.GetUserAsync(User);
            ICollection<Company> companies = null;
            if (await _userManager.IsInRoleAsync(user, "Super Admin") || await _userManager.IsInRoleAsync(user, "Admin"))
            {
               companies = await _companyRepo.GetAllCompanies();
            }
            else
            {
                companies = await _companyRepo.GetAllCompaniesByEmployer(_userManager.GetUserId(User));
            }
            
            foreach (var company in companies)
            {
                var row = new ListCompaniesViewModel
                {
                    Id = company.Id,
                    Name = company.Name,
                    Email = company.Email,
                    Website = company.Website,
                    City = company.City,
                    Country = company.Country
                };

                model.ListOfCompanies.Add(row);
            }

            return View(model);
        }
        // Company (POST) ---------------------------------------------------------------------
        [HttpPost]
        public async Task<IActionResult> Company(CompanyViewModel model, int? id)
        {
            if (ModelState.IsValid)
            {
                var company = new Company
                {
                    Name = model.Name,
                    Email = model.Email,
                    Website = model.Website,
                    Street = model.Street,
                    City = model.City,
                    Country = model.Country,
                    CompanyCertificate = Utils.UploadFile(model.CompanyCertificate, model.ExistingCertificate, _hostingEnvironment, "Certificates"),
                    Logo = Utils.UploadFile(model.Logo, model.ExistingLogo, _hostingEnvironment, "logos"),
                    EmployerId = _userManager.GetUserId(User)
                };

                // id value is binding from the edit view 
                bool result;
                if (id.HasValue)
                {
                    company.Id = (int)id;
                    result = await _companyRepo.UpdateCompany(company);
                }
                else
                {
                    result = await _companyRepo.AddCompany(company);
                }
                
                if (!result)
                {
                    _logger.LogError($"Error saving company to database!");
                    ViewBag.ErrorMessage = "Failed to save company to database!";
                }

CareersListing/Views/Employer/Company.cshtml
@model CompanyViewModel
@{
    ViewBag.Title = "Manage Company";
    Layout = "../Administration/_AdminLayout";
    var sn = 0;
}



<div class="row">

    <!-- left column -->
    <div class="col-sm-12">
        <!-- general form elements -->
        <div class="card card-primary card-outline">

                <div class="row p-3">
                    <!-- general form elements -->
                    <div class="col-md-5">
                        <div>@ViewBag.ErrorMessage</div>
                        <!-- form start -->
                        <form role="form" enctype="multipart/form-data" method="post" asp-action="Company">
                            <div class="no-bullet"  asp-validation-summary="ModelOnly"></div>
                            <div class="card-body">
                                <input asp-for="ExistingLogo" hidden />
                                <input asp-for="ExistingCertificate" hidden />

                                <div class="row mb-2">
                                    <div class="col-sm-12">
                                        <span asp-validation-for="Name" class="text-danger"></span>
                                        <div class="form-group">
                                            <label asp-for="Name"></label>
                                            <input asp-for="Name" placeholder="Company Name" class="form-control" />
                                        </div>
                                    </div>
                                </div>
                                <div class="row mb-2">
                                    <div class="col-sm-6">
                                        <span asp-validation-for="Email" class="text-danger"></span>
                                        <div class="form-group">
                                            <label asp-for="Email"></label>
                                            <input asp-for="Email" placeholder="Email" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <span asp-validation-for="Website" class="text-danger"></span>
                                        <div class="form-group">
                                            <label asp-for="Website"></label>
                                            <input asp-for="Website" placeholder="Website" class="form-control" />
                                        </div>
                                    </div>
                                </div>

                                <div class="row mb-2">
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            <label asp-for="Street"></label>
                                            <input asp-for="Street" placeholder="Street" class="form-control" />
                                        </div>
                                        <span asp-validation-for="Street" class="text-danger"></span>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            <label asp-for="City"></label>
                                            <input asp-for="City" placeholder="City" class="form-control" />
                                        </div>
                                        <span asp-validation-for="City" class="text-danger"></span>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            <label asp-for="Country"></label>
                                            <input asp-for="Country" placeholder="Country" class="form-control" />
                                        </div>
                                        <span asp-validation-for="Country" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="row mb-2">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label asp-for="Logo" class="col-form-label"></label>
                                            <div class="">
                                                <div class="custom-file col-sm-12 ">
                                                    <input asp-for="Logo" type="file" class="custom-file-input form-control" />
                                                    <label class="custom-file-label">Pick a logo</label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label asp-for="CompanyCertificate" class="col-form-label"></label>
                                            <div class="">
                                                <div class="custom-file col-sm-12 ">
                                                    <input asp-for="CompanyCertificate" type="file" class="custom-file-input form-control" />
                                                    <label class="custom-file-label">Upload PDF</label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                                <a asp-action="Users" asp-controller="Administration" class="btn btn-danger">Cancel</a>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->
                  
                    <div class="col-md-7">
                        <div class="card mt-5" style="overflow:auto; min-height:450px; min-height:450px;">
                            @if(Model.ListOfCompanies.Count > 0)
                            {
                                <table class="table projects">
                                    <thead>
                                        <tr class="bg-gradient-gray text-white-50" style="">
                                            <th style="width: 5%;" class="text-center">#</th>
                                            <th style="width: 20%;">
                                                COMPANY
                                            </th>
                                            <th style="width: 30%;" class="text-center">
                                                WEBSITE & EMAIL
                                            </th>
                                            <th style="width: 20%;" class="text-center">
                                                LOCATION
                                            </th>
                                            <th style="width: 25%;" class="text-center">
                                                MANAGE
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody class="text-muted">
                                        @foreach (var company in Model.ListOfCompanies)
                                        {
                                            sn += 1;
                                            <tr>
                                                <td class="text-center">@sn</td>
                                                <td>
                                                    <div>@company.Name</div>
                                                </td>
                                                <td class="text-center">
                                                    <div class="border-bottom pb-2"><small><a href="#">@company.Website</a></small></div>
                                                    <div><small><a href="#">@company.Email</a></small></div>
                                                </td>
                                                <td class="text-center">
                                                    @company.City, @company.Country
                                                </td>
                                                <td>
                                                    <div class="text-center">
                                                        <form method="post" asp-action="DeleteCompany" asp-controller="Employer" asp-route-id="@company.Id">
                                                            <a asp-action="Company" asp-controller="Employer" asp-route-id="@company.Id"
                                                               style="font-size:14px;" class="btn btn-sm btn-primary m-1"> Edit </a>

                                                            <button type="submit" class="btn btn-sm btn-danger m-1" style="font-size:14px;"
                                                                    onclick="return confirm('Please confirm your action to delete : @company.Name');">
                                                                Delete
                                                            </button>

                                                        </form>
                                                    </div>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            }
                            else
                            {
                                <div style="font-size:26px; padding-top:200px;" class="text-center text-black-50">No company record added yet!</div>
                                <div class="text-center">
                                    <i class="fa fa-building text-black-50" style="font-size:70px;"></i>
                                </div>
                            }

                        </div>
                    </div>
                    <!-- /.content-wrapper -->
                </div>
                <!-- /.content-wrapper -->

          
        </div>
    </div>
</div>


@section Scripts{
    <script>
        // when document is ready
        // run the anonymous function
        // on change on custom-file-input element
        // get the value from the element and split it then pop out the last item
        // add the popped out item to the label element
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var filename = $(this).val().split("\\").pop();
                $(this).next('.custom-file-label').html(filename);
            })
        })
    </script>
}